import type { Metadata } from "next";
import  '../styles/globals.scss';
import { AuthProvider } from "./auth-provider";
import { Raleway } from "next/font/google";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const raleway = Raleway({ subsets: ["latin"], weight: '300' });


export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es">
            <body className={raleway.className}>
                <AuthProvider>
                    {children}
                </AuthProvider>
            </body>
        </html>
    );
}
